### ISSUE TITLE
Si le humans.txt n'est pas à la racine, fallback vers le noeud courant

### ISSUE THREAD

**Issue by borisschapira** [joachimesque/humanstxt-webextension#1]
Exemple: https://sudweb.fr/2018/humans.txt 👍

**Comment by joachimesque** [comment]
Après avoir regardé un petit peu, ça va être un peu plus dur que je ne le pensais au premier abord

**Comment by joachimesque** [comment]
C'est maintenant en test, je pense m'être un peu emmêlé les pinceaux (il fait trop souvent la requête), mais ça marche pour sudweb.fr/2018.

En revanche c'est absolument pas raccord avec le standard http://humanstxt.org/Standard.html 😄

**Comment by borisschapira** [comment]
👍
