### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by mcorossigo** [joachimesque/humanstxt-webextension#3]
Hello @joachimesque 
I was planning to put up a PR with some ideas on how to improve caching (right now the extension make a request for every tab update, even switch), when I saw that the extension code (v1.3 ) actually released is quite behind the master branch, which seems to be shipping a couple of improvements.

Can I ask then, what is your plan about it?

**Comment by joachimesque** [comment]
hi @mcorossigo, thanks for your interest! I haven't had time to improve the extension. Please don't hesitate to open Pull Requests with your suggestions and improvement! I know that the caching is quite bad currently, but I didn't have the time or the knowledge to improve it well enough, so any help will be appreciated. Thanks!
